version: "3"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/var/www/html
      - ./nginx-create-ssl-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --force-renewal --webroot-path=/var/www/html -d toucheatapp.com  --webroot-path=/var/www/html -d api.toucheatapp.com --email tv.lidor@gmail.com --agree-tos --no-eff-email --staging --allow-subset-of-names
volumes:
  certbot-etc:
  certbot-var:
  web-root: