version: "3"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./prod:/etc/nginx/conf.d
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api
      - app
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api
      - app
    command: certonly --webroot --force-renewal --webroot-path=/var/www/html -d toucheatapp.com  --webroot-path=/var/www/html -d api.toucheatapp.com --email tv.lidor@gmail.com --agree-tos --no-eff-email --staging --allow-subset-of-names
  api:
    image: lidoravitan/toucheat-server
    environment:
      NODE_ENV: "production"
  app:
    image: lidoravitan/toucheat-admin-fed
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
volumes:
  certbot-etc:
  certbot-var:
  web-root: